# Generated by Django 3.2 on 2023-01-26 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0003_auto_20230127_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='entrytime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
