# Generated by Django 3.2 on 2023-01-26 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_alter_record_entrytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='entrytime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='exittime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
